<?php

$labels = array();
$labels['autoresponder'] = 'Autoodpowiedź';
$labels['autorespondersubject'] = 'Temat';
$labels['autorespondermessage'] = 'Wiadomość';
$labels['autoresponderdate'] = 'Ważne do';
$labels['autoresponderdatefrom'] = 'Ważne od';
$labels['autoresponderenabled'] = 'Włączone';
$labels['dateformat'] = 'rrrr/mm/dd';
$labels['and'] = 'i';
$labels['autoresponder'] = 'Wakacje';

$messages                            = array();
$messages['dateformatinconsistency'] = 'Nieprawidłowy format daty';
$messages['entervalidmonth']         = 'Wprowadź poprawny miesiąc.';
$messages['entervalidday']           = 'Wprowadź poprawny dzień.';
$messages['enterfordigityear']       = 'Wprowadź czterocyfrowy rok';
$messages['entervaliddate']          = 'Wprowadź prawidłową datę.';
$messages['dateinpast']              = 'Ta data nie znajduje się w przyszłości. Data wygaśnięcia zostanie wyłączona!';
$messages['subjectempty']            = 'Wprowadź temat';
$messages['demoaccount']             = 'To konto testowe, autoodpowiedź jest niedostępna.';

?>
